decision:
  en: "You are at a math conference and meet different mathematicians. Do they produce research data?"
  de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten?"
prompt:
  en: "You are at a math conference and meet different mathematicians. Do they produce research data? Try to find out!"
  de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten? Versuche, das herauszufinden!"
initFlags:
  - inc.citizenBraid
  - inc.citizenPunk
  - inc.lawyer
npcs:
  mayor:
    name:
      en: "Felicia Homestedt"
      de: "Felicia Homestedt"
    spawn: { x: 3240, y: 2974 }
    dialogue:
    - type: sequence
      items:
        - text:
            en: "I am a topologist."
            de: "..."
  robot:
    name:
      en: "Robot"
      de: "Roboter"
    spawn: { x: 3540, y: 2974 }
    dialogue:
      - type: random
        items:
          - text:
              en: "“Mathematics is the queen and servant of sciences”, according to a quote by Carl F. Gauss."
              de: "..."
          - text:
              en: "Is Mathematics even a science?"
              de: "..."
          - text:
              en: "Research data are not only empirical records."
              de: "..."
          - text:
              en: "In modern mathematical research, we can find many types of data."
              de: "..."
          - text:
              en: "One key difference between mathematics and other sciences is the existence of proofs."
              de: "..."
          - text:
              en: "Have you subscribed to the MaRDI newsletter, yet?"
              de: "..."
          - text:
              en: "Mathematics is not especially well placed in terms of managing research data and software in comparison to other fields."
              de: "..."
          - text:
              en: "Data must be accompanied by rich metadata that describes it."
              de: "..."
          - text:
              en: "Storing and archiving research data is not a trivial matter and should be planned carefully."
              de: "..."
          - text:
              en: "Information is data tagged with meaning."
              de: "..."
          - text:
              en: "Reusing knowledge is ingrained in the practice of scientific research as the basis of verifiability."
              de: "..."
  citizenBraid:
    name:
      en: "MaRDIan"
      de: "MaRDIaner*in"
    spawn: { x: 2673, y: 3130 }
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
          de: "..."   
  citizenPunk:
    name:
      en: "Statistician"
      de: "Statistiker*in"
    spawn: { x: 3671, y: 2930 }
    dialogue:
      - text:
          en: "I am a statistician."
          de: "Ich bin Statistikerin"
  citizenPuan:
    name:
      en: "Librarian"
      de: "Bibliothekar*in"
    spawn: { x: 4000, y: 3150 }
    dialogue:
      - text:
          en: "I am a librarian."
          de: "Ich bin Bibliothekar*in"
  citizenBlue:
    name:
      en: "MaRDIan"
      de: "Mardianer*in"
    spawn: { x: 2553, y: 3130 }
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
          de: "..."
  citizenWheelchair:
    name:
      en: "Composer"
      de: "Komponistin"
    spawn: { x: 6128, y: 2330 }
    dialogue:
      - text:
          en: "We need to ensure that these AI cameras respect our citizens' privacy and civil liberties."
          de: "Wir müssen sicherstellen, dass diese KI-Kameras die Privatsphäre und die Rechte von uns Bürger*innen respektieren."
  lawyer:
    name:
      en: "Algebraist"
      de: "Algebraiker*in"
    spawn: { x: 2803, y: 2915 }
    dialogue:
      - text:
          en: "I am an algebraist."
          de: "..."
quests:
  favor:
    npc: mayor
    mood: interrogation
    available:
      dialogue:
        - type: sequence
          items:
            - text:
                en: "I am a topologist."
                de: "..."
            - text:
                en: "I publish articles and draw example images."
                de: "..."
            - text:
                en: "Would you help me find out, if this is considered data?"
              responses:
                - text:
                    en: "No, sorry. I am busy writing an important proposal. Goodbye."
                    de: "..."
                  thenText:
                    en: "Bye, bye. Feel free to chat again anytime."
                    de: "..."
                - text:
                    en: "Sure, I will help you."
                    de: "..."
                  thenText:
                    en: "Thank you!"
                    de: "..."
                  set: [ 'quest.favor.active' ]
    stages:
      - cond: 'COUNT("op.favor") >= 2'
        prompt:
          en: "You can let Felicia Homestedt know."
          de: "Du kannst Felicia Homestedt Bescheid geben."
        target: mayor
        dialogues:
          mayor:
            - text:
                en: "Good to know: articles and drawings are data."
                de: "..."
              set: [ 'quest.favor.done', 'pnt.empathy.favor' ]
      - prompt:
          en: "Find out if articles and drawings are data."
          de: "..."
        counter:
          expression: 'COUNT("op.favor")'
          max: 2
          icon: happy
        dialogues:
          mayor:
            - text:
                en: "I am not sure, if articles and drawings are considered data."
                de: "..."
          lawyer:
            - text:
                en: "I’m pretty sure, articles are data. To be 100% sure, ask the MaRDI help desk."
                de: "..."
          citizenBraid:
            - text:
                en: "Documents (articles, books) and their constituent parts (theorems, proofs, formulas…) are data. Treating mathematical texts as data (and not only as mere containers where one deposits ideas in written form) recognizes that mathematical texts deserve the same treatment as other forms of structured data. In particular, FAIR principles and data management plans also apply to texts."
                de: "..."
              set: [ 'op.favor.citizenBraid' ]
          citizenBlue:
            - text:
                en: "Visualizations and examples are data. Examples and visual realizations of mathematical objects (including images, animations, and other types of graphics) can be very intricate and have an enormous value for understanding and developing a theory. Although examples and visualizations can be omitted in more spartan literature, if provided, they deserve a full research data curation as other research data essential to logical proofs."
                de: "..."
              set: [ 'op.favor.citizenHipster' ]
          citizenPunk:
            - text:
                en: "I don't think drawings are data. But I'm not sure. You should ask the MaRDI help desk."
                de: "..."
          citizenPuan:
            - text:
                en: "Articles are data. For details and also for drawings, please consult with the the MaRDI help desk."
                de: "..."
ending:
  dialogue:
    - type: sequence
      items:
        - type: first
          items:
            - cond: 'COUNT("op.favor") >= 2'
              class: 'citizensEmpowered'
              type: sequence
              items:
                - text:
                    en: 'You found out about the data types of documents as well as visuaizations and examples.'
                    de: '...'
                - text:
                    en: "Good to know, that articles are data, and example drawings as well."
                    de: "..."
            - type: sequence
              class: 'citizensAngry'
              items:
                - text:
                    en: "You did not find out if articles or exampe drawings are data."
                    de: "..."
                - type: first
                  items:
                    - cond: 'quest.video.done'
                      class: 'citizensSad'
                      text:
                        en: "After a series of social media posts exposed their many issues, a judge stopped their use. The government still has to pay for them while the problems are fixed."
                        de: "Nachdem eine Reihe von Social Media-Posts ihre vielen Probleme aufgedeckt hatten, hat ein Richter ihren Einsatz gestoppt. Die Stadt muss immer noch für sie bezahlen, während die Probleme behoben werden."
