decision:
  en: "You are at a math conference and meet different mathematicians. Do they produce research data?"
  de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten?"
prompt:
  en: "You are at a math conference and meet different mathematicians. Do they produce research data? Try to find out!"
  de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten? Versuche, das herauszufinden!"
initFlags:
  - inc.citizenBraid
  - inc.citizenPunk
  - inc.lawyer
npcs:
  mayor:
    name:
      en: "Felicia Homestedt"
      de: "Felicia Homestedt"
    spawn: { x: 3240, y: 2974 }
    dialogue:
    - type: sequence
      items:
        - text:
            en: "I am a topologist."
            de: "..."
  robot:
    name:
      en: "Robot"
      de: "Roboter"
    spawn: { x: 3540, y: 2974 }
    dialogue:
      - type: random
        items:
          - text:
              en: "“Mathematics is the queen and servant of sciences”, according to a quote by Carl F. Gauss."
              de: "..."
          - text:
              en: "Is Mathematics even a science?"
              de: "..."
          - text:
              en: "Research data are not only empirical records."
              de: "..."
          - text:
              en: "In modern mathematical research, we can find many types of data."
              de: "..."
          - text:
              en: "One key difference between mathematics and other sciences is the existence of proofs."
              de: "..."
          - text:
              en: "Have you subscribed to the MaRDI newsletter, yet?"
              de: "..."
          - text:
              en: "Mathematics is not especially well placed in terms of managing research data and software in comparison to other fields."
              de: "..."
          - text:
              en: "Data must be accompanied by rich metadata that describes it."
              de: "..."
          - text:
              en: "Storing and archiving research data is not a trivial matter and should be planned carefully."
              de: "..."
          - text:
              en: "Information is data tagged with meaning."
              de: "..."
          - text:
              en: "Reusing knowledge is ingrained in the practice of scientific research as the basis of verifiability."
              de: "..."
          - text:
              en: "Access to research information is the most fundamental principle for spreading science across the scientific community and society."
              de: "..."
  citizenBraid:
    name:
      en: "MaRDIan"
      de: "MaRDIaner*in"
    spawn: { x: 2673, y: 3130 }
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
          de: "..."   
  citizenPunk:
    name:
      en: "Statistician"
      de: "Statistiker*in"
    spawn: { x: 3671, y: 2930 }
    dialogue:
      - text:
          en: "I am a statistician."
          de: "Ich bin Statistikerin"
  citizenPuan:
    name:
      en: "Librarian"
      de: "Bibliothekar*in"
    spawn: { x: 4000, y: 3150 }
    dialogue:
      - text:
          en: "I am a librarian."
          de: "Ich bin Bibliothekar*in"
  citizenBlue:
    name:
      en: "MaRDIan"
      de: "Mardianer*in"
    spawn: { x: 2553, y: 3130 }
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
          de: "..."
  citizenWheelchair:
    name:
      en: "Composer"
      de: "Komponistin"
    spawn: { x: 6128, y: 2330 }
    dialogue:
      - text:
          en: "We need to ensure that these AI cameras respect our citizens' privacy and civil liberties."
          de: "Wir müssen sicherstellen, dass diese KI-Kameras die Privatsphäre und die Rechte von uns Bürger*innen respektieren."
  lawyer:
    name:
      en: "Algebraist"
      de: "Algebraiker*in"
    spawn: { x: 2803, y: 2915 }
    dialogue:
      - text:
          en: "I am an algebraist."
          de: "..."
quests:
  favor:
    npc: mayor
    mood: interrogation
    available:
      dialogue:
        - type: sequence
          items:
            - text:
                en: "I am a topologist."
                de: "..."
            - text:
                en: "I publish articles and draw example images."
                de: "..."
            - text:
                en: "Would you help me find out, if this is considered data?"
              responses:
                - text:
                    en: "No, sorry. I am busy writing an important proposal. Goodbye."
                    de: "..."
                  thenText:
                    en: "Bye, bye. Feel free to chat again anytime."
                    de: "..."
                - text:
                    en: "Sure, I will help you."
                    de: "..."
                  thenText:
                    en: "Thank you!"
                    de: "..."
                  set: [ 'quest.favor.active' ]
    stages:
      - cond: 'COUNT("op.favor") >= 2'
        prompt:
          en: "You can let Felicia Homestedt know."
          de: "Du kannst Felicia Homestedt Bescheid geben."
        target: mayor
        dialogues:
          mayor:
            - text:
                en: "Good to know: articles and drawings are data."
                de: "..."
              set: [ 'quest.favor.done', 'pnt.empathy.favor' ]
      - prompt:
          en: "Find out if articles and drawings are data."
          de: "..."
        counter:
          expression: 'COUNT("op.favor")'
          max: 2
          icon: happy
        dialogues:
          mayor:
            - text:
                en: "I am not sure, if articles and drawings are considered data."
                de: "..."
          lawyer:
            - text:
                en: "I’m pretty sure, articles are data. To be 100% sure, ask the MaRDI help desk."
                de: "..."
          citizenBraid:
            - text:
                en: "Documents (articles, books) and their constituent parts (theorems, proofs, formulas…) are data. Treating mathematical texts as data (and not only as mere containers where one deposits ideas in written form) recognizes that mathematical texts deserve the same treatment as other forms of structured data. In particular, FAIR principles and data management plans also apply to texts."
                de: "..."
              set: [ 'op.favor.citizenBraid' ]
          citizenBlue:
            - text:
                en: "Visualizations and examples are data. Examples and visual realizations of mathematical objects (including images, animations, and other types of graphics) can be very intricate and have an enormous value for understanding and developing a theory. Although examples and visualizations can be omitted in more spartan literature, if provided, they deserve a full research data curation as other research data essential to logical proofs."
                de: "..."
              set: [ 'op.favor.citizenHipster' ]
          citizenPunk:
            - text:
                en: "I don't think drawings are data. But I'm not sure. You should ask the MaRDI help desk."
                de: "..."
          citizenPuan:
            - text:
                en: "Articles are data. For details and also for drawings, please consult with the the MaRDI help desk."
                de: "..."
  publish:
    npc: lawyer
    mood: exclamation
    available:
      dialogue:
        - type: sequence
          items:
            - text:
                en: "Hi, I am an algebraist. I just published a paper and some software code."
                de: "..."
            - text:
                en: "I used my ORCID iD and my Zenodo account."
                de: "..."
            - text:
                en: "Would you like to have your own ORCID iD and Zenodo account?"
                de: "..."
              responses:
                - text:
                    en: "Sure, I will will try to set it up right now."
                    de: "..."
                  thenText:
                    en: "Great! If you need more information about ORCID or Zenodo, ask at the MaRDI help desk."
                    de: "..."
                  set: [ 'quest.publish.active' ]
                - text:
                    en: "No, sorry, I have no idea. I am too old for this fancy internet stuff."
                    de: "..."
                  thenText:
                    en: "You might want to check out the first issue of the MarDI newsletter to get an introduction to the topic."
                    de: "..."
                - text:
                    en: "Actually, I already have both. But I'll play along."
                    de: "..."
                  thenText:
                    en: "What fun!"
                    de: "..."
                  set: [ 'quest.publish.active' ]
    stages:
      - cond: 'found.publish.orcid & ^found.publish.zenodo'
        prompt:
          en: "You got an ORCID iD. Now you can create a Zenodo account to publish your paper."
          de: "..."
        dialogues:
          lawyer:
            - text:
                en: "Congratulations to your ORCID iD. You need to create a Zenodo account now."
                de: "..."
          citizenPunk:
            - text:
                en: "Of course, I have a Zenodo account. But I am too busy to help you. Ask the robot."
                de: "..."
          robot:
            - text:
                en: "I am happy to create a Zenodo account for you. All done, congratulations."
                de: "..."
              set: [ 'found.publish.zenodo', 'quest.publish.done', 'pnt.information.publish' ]
          citizenBlue:
            - text:
                en: "Zenodo is a general-purpose open repository. It allows researchers to deposit research papers, data sets, research software, reports, and any other research related digital artefacts. The robot can create an account for you."
                de: "..."
          citizenBraid:
            - text:
                en: "You already got your ORCID iD. However, if you are still wondering what it is: ORCID, wich stands for Open Researcher and Contributor ID, is a global, not-for-profit organization. It provides a persistent digital identifier (an ORCID iD) that you own and control, and that distinguishes you from every other researcher."
                de: "..."
          mayor:
            - text:
                en: "Congratulations to your ORCID iD."
                de: "..."
          citizenPuan:
            - text:
                en: "I cannot help you at the moment. I need to prepare, classify and maintain our media collection."
                de: "..."
      - cond: '^found.publish.orcid & ^found.publish.zenodo'
        prompt:
          en: "Create an ORCID iD."
          de: "..."
        dialogues:
          lawyer:
            - text:
                en: "You need to create an ORCID iD first."
                de: "..."
          robot:
            - text:
                en: "Come back when you have your ORCID iD. Then we can create your Zenodo account."
                de: "..."
          citizenBlue:
            - text:
                en: "Zenodo is a general-purpose open repository. It allows researchers to deposit research papers, data sets, research software, reports, and any other research related digital artefacts."
                de: "..."
          citizenPuan:
            - text:
                en: "I am happy to create an ORCID iD with you. We can use one of the library tablets with free WiFi."
                de: "..."
              set: [ 'found.publish.orcid' ]
          citizenBraid:
            - text:
                en: "ORCID, wich stands for Open Researcher and Contributor ID, is a global, not-for-profit organization. It provides a persistent digital identifier (an ORCID iD) that you own and control, and that distinguishes you from every other researcher. You can go to the library to get an iD."
                de: "..."
          mayor:
            - text:
                en: "I got my own ORCID iD at the library."
                de: "..."
          citizenPunk:
            - text:
                en: "Please, don't disturb me. I am coding..."
                de: "..."
ending:
  dialogue:
    - type: sequence
      items:
        - type: first
          items:
            - cond: 'COUNT("op.favor") >= 2'
              class: 'citizensEmpowered'
              type: sequence
              items:
                - text:
                    en: 'You found out about the data types of documents as well as visuaizations and examples.'
                    de: '...'
                - text:
                    en: "Good to know, that articles are data, and example drawings as well."
                    de: "..."
            - type: sequence
              class: 'citizensAngry'
              items:
                - text:
                    en: "You did not find out if articles or example drawings are data."
                    de: "..."
            - cond: 'found.publish.orcid & found.publish.zenodo'
              class: 'citizensEmpowered'
              type: sequence
              items:
                - text:
                    en: 'You created an ORCID iD and a Zenodo account.'
                    de: '...'
                - text:
                    en: "Good to know, that articles are data, and example drawings as well."
                    de: "..."
            - type: sequence
              class: 'citizensAngry'
              items:
                - text:
                    en: "You did not create a Zenodo account."
                    de: "..."
