decision:
  en: "You are at a math conference and meet different mathematicians. Do they produce research data?"
  de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten?"
prompt:
  en: "You are at a math conference and meet different mathematicians. Do they produce research data? Try to find out!"
  de: "Du bist auf einer Mathe-Konferenz und triffst verschiedene Mathematiker*innen. Produzieren sie Forschungsdaten? Versuche, das herauszufinden!"
initFlags:
  - inc.mayor
  - inc.policeChief
  - inc.citizenCool
npcs:
  mayor:
    name:
      en: "Felicia Homestedt"
      de: "Felicia Homestedt"
    spawn: { x: 3240, y: 2974 }
    dialogue:
    - type: sequence
      items:
        - text:
            en: "I am a topologist."
            de: "..."
  tourist:
    name:
      en: "Tourist"
      de: "Tourist"
    spawn: { x: 2901, y: 2050 }
    dialogue:
      - text:
          en: "Surveillance cameras in my country reduced crime enormously."
          de: "In meinem Land haben Überwachungskameras die Kriminalität enorm reduziert."
  robot:
    name:
      en: "Robot"
      de: "Roboter"
    spawn: { x: 5748, y: 2340 }
    dialogue:
      - type: random
        items:
          - text:
              en: "Technology has already invented bikes that can’t be stolen: cars!"
              de: "Die Technologie hat bereits Fahrräder erfunden, die nicht gestohlen werden können: Autos!"
          - text:
              en: "Perhaps you would notice crime if you weren’t so busy composting."
              de: "Vielleicht würde dir die Kriminalität auffallen, wenn du nicht so faul herumhängen würdest."
          - text:
              en: "I know how to solve crime with AI: get me a badge and a gun."
              de: "Ich weiß, wie man Verbrechen mit KI löst: Gib mir einen Polizeimarke und eine Waffe."
  citizenBraid:
    name:
      en: "MaRDIan"
      de: "MaRDIaner*in"
    spawn: { x: 2673, y: 3130 }
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
          de: "..."   
  citizenPunk:
    name:
      en: "Statistician"
      de: "Statistiker*in"
    spawn: { x: 3671, y: 2930 }
    dialogue:
      - text:
          en: "I am a statistician."
          de: "Ich bin Statistikerin"
  citizenBlue:
    name:
      en: "MaRDIan"
      de: "Mardianer*in"
    spawn: { x: 2553, y: 3130 }
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
          de: "..."
  constructionWorker:
    name:
      en: "Engineer"
      de: "Ingenieurin"
    spawn: { x: 5846, y: 3130 }
    dialogue:
      - text:
          en: "Our personal data is at stake with AI cameras."
          de: "Unsere persönlichen Daten stehen bei KI-Kameras auf dem Spiel."
  citizenQueen:
    name:
      en: "Citizen"
      de: "Bürgerin"
    spawn: { x: 5660, y: 970 }
    dialogue:
      - text:
          en: "Bike theft is impacting on our community's sense of trust."
          de: "Die Fahrraddiebstähle beeinträchtigen das Vertrauen in unsere Gemeinschaft."
  citizenRanger:
    name:
      en: "Ranger"
      de: "Ranger"
    spawn: { x: 896, y: 2290 }
    dialogue:
      - text:
          en: "Instead of spending money on cameras the city should fund the police department properly."
          de: "Anstatt Geld für Kameras auszugeben, sollte die Stadt die Polizeiabteilung ordentlich finanzieren."
  citizenWheelchair:
    name:
      en: "Composer"
      de: "Komponistin"
    spawn: { x: 6128, y: 2330 }
    dialogue:
      - text:
          en: "We need to ensure that these AI cameras respect our citizens' privacy and civil liberties."
          de: "Wir müssen sicherstellen, dass diese KI-Kameras die Privatsphäre und die Rechte von uns Bürger*innen respektieren."
  citizenChamp:
    name:
      en: "Citizen"
      de: "Bürgerin"
    spawn: { x: 1946, y: 2770 }
    dialogue:
      - text:
          en: "AI will only provide data. Can the police act on it?"
          de: "KI wird nur Daten liefern. Kann die Polizei diese nutzen?"
  lawyer:
    name:
      en: "Algebraist"
      de: "Algebraiker*in"
    spawn: { x: 2803, y: 2915 }
    dialogue:
      - text:
          en: "I am an algebraist."
          de: "..."
quests:
  favor:
    npc: mayor
    mood: interrogation
    available:
      dialogue:
        - type: sequence
          items:
            - text:
                en: "I am a topologist."
                de: "..."
            - text:
                en: "I publish articles and draw example images."
                de: "..."
            - text:
                en: "Would you help me find out, if this is considered data?"
              responses:
                - text:
                    en: "No, sorry. I am busy writing an important proposal. Goodbye."
                    de: "..."
                  thenText:
                    en: "Bye, bye. Feel free to chat again anytime."
                    de: "..."
                - text:
                    en: "Sure, I will help you."
                    de: "..."
                  thenText:
                    en: "Thank you!"
                    de: "..."
                  set: [ 'quest.favor.active' ]
    stages:
      - cond: 'COUNT("op.favor") >= 2'
        prompt:
          en: "Du kannst Felicia Homestedt Bescheid geben."
          de: "..."
        target: mayor
        dialogues:
          mayor:
            - text:
                en: "Good to know: articles and drawings are data."
                de: "..."
              set: [ 'quest.favor.done', 'pnt.empathy.favor' ]
      - prompt:
          en: "Find out if articles and drawings are data."
          de: "..."
        counter:
          expression: 'COUNT("op.favor")'
          max: 2
          icon: happy
        dialogues:
          mayor:
            - text:
                en: "I am not sure, if articles and drawings are considered data."
                de: "..."
          lawyer:
            - text:
                en: "I’m pretty sure, articles are data. To be 100% sure, ask the MaRDI help desk."
                de: "..."
          citizenBraid:
            - text:
                en: "Documents (articles, books) and their constituent parts (theorems, proofs, formulas…) are data. Treating mathematical texts as data (and not only as mere containers where one deposits ideas in written form) recognizes that mathematical texts deserve the same treatment as other forms of structured data. In particular, FAIR principles and data management plans also apply to texts."
                de: "..."
              set: [ 'op.favor.citizenBraid' ]
          citizenBlue:
            - text:
                en: "Visualizations and examples are data. Examples and visual realizations of mathematical objects (including images, animations, and other types of graphics) can be very intricate and have an enormous value for understanding and developing a theory. Although examples and visualizations can be omitted in more spartan literature, if provided, they deserve a full research data curation as other research data essential to logical proofs."
                de: "..."
              set: [ 'op.favor.citizenHipster' ]
          citizenPunk:
            - text:
                en: "I don't think drawings are data. But I'm not sure. You should ask the MaRDI help desk."
                de: "..."
ending:
  dialogue:
    - type: sequence
      items:
        - type: first
          items:
            - cond: 'quest.committee.done'
              class: 'citizensEmpowered'
              type: sequence
              items:
                - text:
                    en: 'The government went ahead with the installation of AI-assisted cameras in key parts of the city.'
                    de: 'Die Regierung hat mit der Installation von KI-unterstützten Kameras in wichtigen Teilen der Stadt begonnen.'
                - text:
                    en: "A civil commitee oversees their correct use. It also proposed improvements to the system, which are being shared with other cities."
                    de: "Ein öffentlicher Ausschuss überwacht ihren korrekten Einsatz. Er schlug auch Verbesserungen des Systems vor, die mit anderen Städten geteilt werden."
            - cond: 'quest.issues.done'
              class: 'citizensNeutral'
              type: sequence
              items:
                - text:
                    en: "The government decided not to install AI-assisted cameras."
                    de: "Die Regierung hat beschlossen, keine KI-unterstützten Kameras zu installieren."
                - text:
                    en: "The mayor realized that more work is needed to make them fair for everyone."
                    de: "Die Bürgermeisterin erkannte, dass mehr Arbeit nötig wäre, um sie gerecht für alle zu machen."
            - cond: 'quest.against.done'
              class: 'citizensSad'
              type: sequence
              items:
                - text:
                    en: 'The government went ahead with the installation of AI-assisted cameras in key parts of the city.'
                    de: 'Die Regierung hat mit der Installation von KI-unterstützten Kameras in wichtigen Teilen der Stadt begonnen.'
                - text:
                    en: 'Bike robberies were reduced, but there are many complaints from innocent people who were wrongly accused.'
                    de: 'Es gab weniger Fahrraddiebstähle, aber viele Beschwerden von Menschen, die zu Unrecht beschuldigt wurden.'
            - type: sequence
              class: 'citizensAngry'
              items:
                - text:
                    en: "The government went ahead with the installation of hundreds of AI-assisted cameras all over the city."
                    de: "Die Regierung hat mit der Installation von Hunderten von KI-unterstützten Kameras in der ganzen Stadt begonnen."
                - type: first
                  items:
                    - cond: 'quest.video.done'
                      class: 'citizensSad'
                      text:
                        en: "After a series of social media posts exposed their many issues, a judge stopped their use. The government still has to pay for them while the problems are fixed."
                        de: "Nachdem eine Reihe von Social Media-Posts ihre vielen Probleme aufgedeckt hatten, hat ein Richter ihren Einsatz gestoppt. Die Stadt muss immer noch für sie bezahlen, während die Probleme behoben werden."
                    - text:
                        en: "Bike robberies are now very rare, but the legal system is overwhelmed with complaints from innocent people who were wrongly accused."
                        de: "Fahrraddiebstähle sind jetzt sehr selten, aber das Rechtssystem ist mit Beschwerden von Menschen überlastet, die zu Unrecht beschuldigt wurden."
